config/routes.rb
Rails.application.routes.draw do
  # 利用者用
  # URL /customers/sign_in ...
  devise_for :end_users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  scope module: :public do
    root to: "homes#top"

    devise_scope :end_user do
      post 'end_users/guest_sign_in', to: 'guests#guest_sign_in'
    end

    resource :end_users, only: [:edit], path_names: { edit: 'information/edit' } do
      get "/" => "end_users#top"
      get "/my_page" => "end_users#show"
      patch "/information" => "end_users#update"
      get "confirm"
      patch "withdraw"
    end

    resources :account_books, only: [:new, :index, :edit, :create, :update, :destroy]
    resources :deposit_balances, only: [:new, :index, :edit, :create, :update, :destroy]
    resources :source_of_incomes, only: [:index, :edit, :create, :update]
    resources :savings_estinations, only: [:index, :edit, :create, :update]
    resources :tags, only: [:create]
    resources :bop_subjects, only: [:new, :show, :index, :edit, :create, :update, :destroy]
    resources :consultations, only: [:index, :show, :new, :create] do
      resources :comments, only: [:create]
      resource :favorites, only: [:create, :destroy]
      collection do
        get "my_index"
        get "search"
      end
    end
    get "favorites/my_index"
  end



  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: "homes#top"
    resources :consultations, only: [:show, :index, :destroy, :edit, :update] do
      resources :comments, only: [:destroy]
      collection do
        get "search"
        get "ai_search"
      end
    end
    resources :end_users, only: [:show, :edit, :update] do
      collection do
        get "search"
      end
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/consultation.rb
class Consultation < ApplicationRecord
  belongs_to :end_user
  has_many :middle_of_tags, dependent: :destroy
  has_many :tags, through: :middle_of_tags
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true


  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    new_tags = sent_tags - current_tags

    # 新しいタグを保存
    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(name: new)
      self.tags << new_post_tag
    end
  end

  #consultationのviewで使用
  def favorited_by?(end_user)
    favorites.exists?(end_user_id: end_user.id)
  end

  #キーワード検索
  def self.search(search)
    if search != nil
      Consultation.where('title LIKE(?) or body LIKE(?)' , "%#{search}%",  "%#{search}%")
    end
  end

  def self.ai_search(score, check)
    if score == "plus"
      if check == ""
        Consultation.where("score >= ?", 0)
      else
        Consultation.where("score >= ?", 0).where(emotion_check: check)
      end
    elsif score == "minus"
      if check == ""
        Consultation.where("score < ?", 0)
      else
        Consultation.where("score < ?", 0).where(emotion_check: check)
      end
    else
      if check == ""
        Consultation.all
      else
        Consultation.where(emotion_check: check)
      end
    end
  end


  #氏名の姓名を合わせるメソッド
  def full_name
    end_user.last_name + ' ' + end_user.first_name
  end

end

app/controllers/admin/consultations_controller.rb
class Admin::ConsultationsController < ApplicationController

  def index
    @consultations = Consultation.all.order(created_at: "DESC").page(params[:page])
  end

  def show
    @consultation = Consultation.find(params[:id])
    @consultation_tags = @consultation.tags
  end

  def edit
    @consultation = Consultation.find(params[:id])
    @consultation_tags = @consultation.tags
  end

  def update
    @consultation = Consultation.find(params[:id])
    @consultation.score = Language.get_data(consultation_params[:body])
    if @consultation.update(consultation_params)
      redirect_to admin_consultation_path(@consultation)
    else
      render :edit
    end
  end

  def destroy
    @consultation = Consultation.find(params[:id])
    @consultation.destroy
    redirect_to admin_consultations_path
  end

  def search
    @consultations = Consultation.all
    if params[:keyword] == ""
      flash[:keyword] = "キーワードを入力してください"
      redirect_to admin_consultations_path
    elsif (params[:keyword])[0] == '#'
      if Tag.search(params[:keyword]).nil?
        @consultation = nil
      else
        @consultation = Tag.search(params[:keyword]).order('created_at DESC').page(params[:page])
      end
    else
      @consultation = Consultation.search(params[:keyword]).order('created_at DESC').page(params[:page])
    end
  end

  def ai_search
    score = params[:score]
    check = params[:check]
    @records = Consultation.ai_search(score, check).page(params[:page]).order(created_at: "DESC")
  end

  private

  def consultation_params
    params.require(:consultation).permit(:title, :body, :emotion_check)
  end
end

app/helpers/admin/consultations_helper.rb
module Admin::ConsultationsHelper
end

app/views/admin/consultations/_search.html.erb
<%= form_with url: search_admin_consultations_path, method: :get do |f| %>
  <div class="form-inline mt-4">
    <%= f.text_field :keyword, class: "form-control col-8" %>
    <%= f.submit "検索", class: "btn btn-secondary col-2 ml-3" %>
  </div>
<% end %>

app/views/admin/consultations/ai_search.html.erb
<%= render "layouts/consultation_index", consultations: @records, search_path: search_admin_consultations_path, ai_search_path: ai_search_admin_consultations_path %>

app/views/admin/consultations/edit.html.erb
<div class="col-md-8 sm-10 mx-auto mt-5">
  <div class="card">
    <div class="m-5">
      <h3>相談内容編集</h3>
      <div class="row mt-4">
        <div class="col-lg-2 col-md-3">相談者</div>
        <div class="col-lg-9 col-md-9"><%= @consultation.full_name %></div>
      </div>
      <%= form_with model: @consultation, url: admin_consultation_path, method: :patch, local: true do |f| %>
        <%= f.label :title, "タイトル", class: "mt-4" %>
        <%= f.text_field :title, class: "form-control " %>
        <% if @consultation.errors.include?(:title) %>
          <p class="text-danger"><%= @consultation.errors.full_messages_for(:title).first %></p>
        <% end %>
        <%= f.label :body, "本文", class: "mt-4" %>
        <%= f.text_area :body, class: "form-control", rows:"7" %>
        <% if @consultation.errors.include?(:body) %>
          <p class="text-danger"><%= @consultation.errors.full_messages_for(:body).first %></p>
        <% end %>
        <div>
          <div class="mt-4" style="display:inline-flex">タグ：</div>
          <div style="display:inline-flex">
            <% @consultation_tags.each do |consultation_tag| %>
              <%= consultation_tag.name %>
            <% end %>
          </div>
        </div>
        <% if @consultation.score < 0 %>
          <div class="col-12 pl-0 mt-4" style="display:inline-flex">
            <p class="my-auto">
              確認状況：<br>
              (感情分析)
            </p>
            <%= f.check_box :emotion_check, class: "col-2 my-auto form-control" %>
          </div>
        <% end %>
        <div class="mx-auto">
          <%= f.submit "内容を更新", class:"col-12 btn btn-secondary mt-5" %>
        </div>
      <% end %>
      <div class="col-12 text-center my-4">
        <%= link_to "相談広場へ戻る", admin_consultations_path %>
      </div>
    </div>
  </div>
</div>

app/views/admin/consultations/index.html.erb
<%= render "layouts/consultation_index", consultations: @consultations, search_path: search_admin_consultations_path, ai_search_path: ai_search_admin_consultations_path %>

app/views/admin/consultations/search.html.erb
<%= render "layouts/consultation_index", consultations: @consultation, search_path: search_admin_consultations_path, ai_search_path: ai_search_admin_consultations_path %>

app/views/admin/consultations/show.html.erb
<div class="col-lg-10 col-md-12 mt-5 mx-auto">
  <div class="card">
    <div class="m-5">
      <div class="">
        <h3>相談詳細</h3>
        <div class="mt-4">
          <div class="row">
            <div class="col-lg-2 col-md-3">相談者</div>
            <div class="col-lg-9 col-md-9"><%= @consultation.full_name %></div>
          </div>
          <div class="row mt-4">
            <div class="col-lg-2 col-md-3">タイトル</div>
            <div class="col-lg-9 col-md-9"><%= @consultation.title %></div>
          </div>
          <div class="row mt-4">
            <div class="col-lg-2 col-md-3 align-top">相談内容</div>
            <div class="col-lg-9 col-md-9"><%= @consultation.body %></div>
          </div>
          <div class="row mt-4">
            <div class="col-lg-2 col-md-3">タグ</div>
            <div class="col-lg-9 col-md-9">
              <% @consultation_tags.each do |consultation_tag| %>
                <%= consultation_tag.name %>
              <% end %>
            </div>
          </div>
        </div>
        <div class="row mt-4">
          <div class="col-lg-2 col-md-3">♥<%= @consultation.favorites.count %> いいね</div>
          <div class="comment-count col-lg-2 col-md-3">
            <p>コメント数：<%= @consultation.comments.count %></p>
          </div>
        </div>
        <% if @consultation.score < 0 %>
          <div class="row mt-4">
            <div class="col-lg-2 col-md-3">感情分析</div>
            <div class="col-lg-9 col-md-9">
              <div style="display:inline-flex">
                <p class="mr-3"><%= @consultation.score %></p>
                <% if @consultation.emotion_check == 1 %>
                  <p>確認済み</p>
                <% else %>
                  <p class="text-danger">未確認</p>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
        <div class="m-3 col-12" style="display:inline-flex">
          <div class="ml-auto mr-3"><%= link_to "編集", edit_admin_consultation_path, class: "btn btn-success" %></div>
          <div class="mr-auto ml-3"><%= link_to "削除", admin_consultation_path, method: :delete, data: { confirm: '削除しますか？' }, class: "btn btn-danger" %></div>
        </div>
        <div class="text-center"><%= link_to "一覧に戻る", admin_consultations_path %></div>
      </div>
      <div class="comment-index">
        <%= render "public/comments/comment-index", consultation: @consultation %>
      </div>
    </div>
  </div>
</div>