config/routes.rb
Rails.application.routes.draw do
  # 利用者用
  # URL /customers/sign_in ...
  devise_for :end_users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  scope module: :public do
    root to: "homes#top"

    devise_scope :end_user do
      post 'end_users/guest_sign_in', to: 'guests#guest_sign_in'
    end

    resource :end_users, only: [:edit], path_names: { edit: 'information/edit' } do
      get "/" => "end_users#top"
      get "/my_page" => "end_users#show"
      patch "/information" => "end_users#update"
      get "confirm"
      patch "withdraw"
    end

    resources :account_books, only: [:new, :index, :edit, :create, :update, :destroy]
    resources :deposit_balances, only: [:new, :index, :edit, :create, :update, :destroy]
    resources :source_of_incomes, only: [:index, :edit, :create, :update]
    resources :savings_estinations, only: [:index, :edit, :create, :update]
    resources :tags, only: [:create]
    resources :bop_subjects, only: [:new, :show, :index, :edit, :create, :update, :destroy]
    resources :consultations, only: [:index, :show, :new, :create] do
      resources :comments, only: [:create]
      resource :favorites, only: [:create, :destroy]
      collection do
        get "my_index"
        get "search"
      end
    end
    get "favorites/my_index"
  end



  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: "homes#top"
    resources :consultations, only: [:show, :index, :destroy, :edit, :update] do
      resources :comments, only: [:destroy]
      collection do
        get "search"
        get "ai_search"
      end
    end
    resources :end_users, only: [:show, :edit, :update] do
      collection do
        get "search"
      end
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @end_users = EndUser.order(id: "ASC").page(params[:page])
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/views/admin/homes/top.html.erb
<div class="col-lg-10 col-md-11 mx-auto mt-5">
  <div class="card">
    <div class="m-5">
      <h3 class="d-inline">利用者一覧画面</h3>
      <%= render "layouts/search", search_path: search_admin_end_users_path %>
      <table class="table mt-5">
        <thead>
          <tr>
            <th>氏名</th>
            <th>フリガナ</th>
            <th class="text-center">会員ステータス</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @end_users.each do |end_user| %>
            <tr>
              <td>
                <%= link_to admin_end_user_path(end_user) do %>
                  <%= end_user.full_name %>
                <% end %>
              </td>
              <td>
                <%= link_to admin_end_user_path(end_user) do %>
                  <%= end_user.full_name_kana %>
                <% end %>
              </td>
              <td class="text-center">
                <% if end_user.is_deleted == false %>
                  <div class="text-danger font-weight-bold">有効</div>
                <% else %>
                  <div class="text-secondary">退会</div>
                <% end %>
              </td>
              <td><%= link_to "編集", edit_admin_end_user_path(end_user), class: "btn btn-secondary" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="mb-5 mx-auto"><%= paginate @end_users %></div>
  </div>
</div>