config/routes.rb
Rails.application.routes.draw do
  # 利用者用
  # URL /customers/sign_in ...
  devise_for :end_users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  scope module: :public do
    root to: "homes#top"

    devise_scope :end_user do
      post 'end_users/guest_sign_in', to: 'guests#guest_sign_in'
    end

    resource :end_users, only: [:edit], path_names: { edit: 'information/edit' } do
      get "/" => "end_users#top"
      get "/my_page" => "end_users#show"
      patch "/information" => "end_users#update"
      get "confirm"
      patch "withdraw"
    end

    resources :account_books, only: [:new, :index, :edit, :create, :update, :destroy]
    resources :deposit_balances, only: [:new, :index, :edit, :create, :update, :destroy]
    resources :source_of_incomes, only: [:index, :edit, :create, :update]
    resources :savings_estinations, only: [:index, :edit, :create, :update]
    resources :tags, only: [:create]
    resources :bop_subjects, only: [:new, :show, :index, :edit, :create, :update, :destroy]
    resources :consultations, only: [:index, :show, :new, :create] do
      resources :comments, only: [:create]
      resource :favorites, only: [:create, :destroy]
      collection do
        get "my_index"
        get "search"
      end
    end
    get "favorites/my_index"
  end



  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: "homes#top"
    resources :consultations, only: [:show, :index, :destroy, :edit, :update] do
      resources :comments, only: [:destroy]
      collection do
        get "search"
        get "ai_search"
      end
    end
    resources :end_users, only: [:show, :edit, :update] do
      collection do
        get "search"
      end
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" class="text-danger">
    <h3>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h3>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<% if alert.present? %>
  <div class="alert alert-danger" role="alert" style="width:26%; margin: 15px 400px;">
    <div id="error_explanation">
      <%= alert %>
      <button type="button" class="close" data-dismiss="alert">&times;</button>
    </div>
  </div>
<% end %>
<% if flash.now[:notice].present? %>
  <%= flash[:notice] %>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>