config/routes.rb
Rails.application.routes.draw do
  # 利用者用
  # URL /customers/sign_in ...
  devise_for :end_users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  scope module: :public do
    root to: "homes#top"

    devise_scope :end_user do
      post 'end_users/guest_sign_in', to: 'guests#guest_sign_in'
    end

    resource :end_users, only: [:edit], path_names: { edit: 'information/edit' } do
      get "/" => "end_users#top"
      get "/my_page" => "end_users#show"
      patch "/information" => "end_users#update"
      get "confirm"
      patch "withdraw"
    end

    resources :account_books, only: [:new, :index, :edit, :create, :update, :destroy]
    resources :deposit_balances, only: [:new, :index, :edit, :create, :update, :destroy]
    resources :source_of_incomes, only: [:index, :edit, :create, :update]
    resources :savings_estinations, only: [:index, :edit, :create, :update]
    resources :tags, only: [:create]
    resources :bop_subjects, only: [:new, :show, :index, :edit, :create, :update, :destroy]
    resources :consultations, only: [:index, :show, :new, :create] do
      resources :comments, only: [:create]
      resource :favorites, only: [:create, :destroy]
      collection do
        get "my_index"
        get "search"
      end
    end
    get "favorites/my_index"
  end



  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: "homes#top"
    resources :consultations, only: [:show, :index, :destroy, :edit, :update] do
      resources :comments, only: [:destroy]
      collection do
        get "search"
        get "ai_search"
      end
    end
    resources :end_users, only: [:show, :edit, :update] do
      collection do
        get "search"
      end
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_consultation_index.html.erb
<% unless admin_signed_in? %>
  <div class="col-lg-10 col-md-11 mx-auto m-5">
    <div class="card">
      <div class="m-5">
        <div class="row">
          <h3 class="col-9 d-flex align-items-center"><%= name %>相談一覧</h3>
          <div class="d-inline" style="">
            <%= link_to "相談する", new_consultation_path, class: "btn btn-secondary" %>
          </div>
        </div>
        <%= render "layouts/search", search_path: search_path %>
        <% if controller.action_name == "search" %>
          <h4 class="mt-4">"<%= params[:keyword] %>"の検索結果</h4>
        <% end %>
        <table class="table mt-5">
          <thead>
            <tr>
              <th class="text-center">相談日時</th>
              <th class="text-center">相談タイトル</th>
              <th class="text-center">タグ</th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% if consultations.nil? || consultations.empty? %>
              <p class="text-danger" style="font-size: 20px;">検索結果はありません</p>
            <% else %>
              <% consultations.each do |consultation| %>
                <tr>
                  <td><%= consultation.created_at.strftime('%Y年%m月%d日 %H時%m分') %></td>
                  <td>
                    <%= link_to consultation_path(consultation) do %>
                      <%= consultation.title.truncate(20) %>
                    <% end %>
                  </td>
                  <td>
                    <% consultation.tags.each do |tag| %>
                      <%= tag.name %>
                    <% end %>
                  </td>
                  <td class="favorite-btn_<%= consultation.id %>">
                    <% unless consultation.end_user_id == current_end_user.id %>
                      <%= render 'public/favorites/favorite-btn', consultation: consultation %>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to consultation_path(consultation) do %>
                      コメント数：<%= consultation.comments.count %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
        <% unless consultations.nil? %>
          <div class="mt-4 d-flex justify-content-center"><%= paginate consultations %></div>
        <% end %>
      </div>
    </div>
  </div>
<% else %>
  <div class="col-lg-10 col-md-11 mx-auto m-5">
    <div class="card">
      <div class="m-5">
        <h3 class="d-inline">相談管理画面</h3>
        <%= render "layouts/search", search_path: search_path %>
        <h5 class="mt-3">感情分析</h5>
        <div class="form-inline">
          <%= form_with url: ai_search_path, method: :get, local: true, class:"col-12 pl-0" do |f| %>
            <%= f.select :score, options_for_select({ "選択してください" => "", "マイナス" => "minus", "プラス" => "plus" }), {}, class: "form-control" %>
            <%= f.select :check, options_for_select({ "選択してください" => "", "未確認" => 0, "確認済" => 1 }), {}, {class: "form-control"} %>
            <%= f.submit '検索', class: "btn btn-secondary col-2 ml-3" %>
          <% end %>
        </div>
        <% if controller.action_name == "search" %>
          <h4 class="mt-4">"<%= params[:keyword] %>"の検索結果</h4>
        <% end %>
        <table class="table mt-5">
          <thead>
            <thead>
              <tr>
                <th class="text-center">相談日時</th>
                <th class="text-center">相談タイトル</th>
                <th class="text-center">タグ</th>
                <th class="text-center" width="90px">感情分析</th>
                <th class="text-center" width="90px">確認状況</th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
              </tr>
            </thead>
          </thead>
          <tbody>
            <% if consultations.nil? || consultations.empty? %>
              <p class="text-danger" style="font-size: 20px;">検索結果はありません</p>
            <% else %>
              <% consultations.each do |consultation| %>
                <tr>
                  <td><%= consultation.created_at.strftime('%Y年%m月%d日 %H時%m分') %></td>
                  <td>
                    <%= link_to admin_consultation_path(consultation) do %>
                      <%= consultation.title.truncate(20) %>
                    <% end %>
                  </td>
                  <td>
                    <% consultation.tags.each do |tag| %>
                      <%= tag.name %>
                    <% end %>
                  </td>
                  <td class="text-center"><%= consultation.score %></td>
                  <td>
                    <% if consultation.score < 0 %>
                      <% if consultation.emotion_check == 1 %>
                        <p>確認済み</p>
                      <% else %>
                        <p class="text-danger">未確認</p>
                      <% end %>
                    <% end %>
                  </td>
                  <td>
                    ♥<%= consultation.favorites.count %>
                  </td>
                  <td>
                    <%= link_to admin_consultation_path(consultation) do %>
                      コメント数：<%= consultation.comments.count %>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to "編集", edit_admin_consultation_path(consultation), class: "btn btn-success" %>
                  </td>
                  <td>
                    <%= link_to "削除", admin_consultation_path(consultation), method: :delete, data: { confirm: '削除しますか？' }, class:  "btn btn-danger" %>
                  </td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
        <% unless consultations.nil? %>
          <div class="mt-4 d-flex justify-content-center"><%= paginate consultations %></div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_error_count.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" class="text-danger">
    <h3>
      <%= I18n.t("errors.messages.error",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h3>
  </div>
<% end %>

app/views/layouts/_error_messages.html.erb
<% if @bop_subject.errors.include?("bop_details") %>
  <div id="error_explanation" class="text-danger">
    <ul>
      <% @bop_subject.errors.full_messages_for("bop_details").each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="padding: 0;">
  <div class="" style="display:inline-flex;">
    <a class="navbar-brand pl-4" href="/">
      <%= image_tag asset_path("logo4.png", alt: "LOGO"), width:"90px", height:"" %>
    </a>
    <div class="my-auto" style="width: 190px; margin: 0;">
      <% if end_user_signed_in? %>
        <span class="navbar-text text_area offset-1" style="width: 190px; margin: 0;">
          ようこそ、<%= current_end_user.last_name %>さん！
        </span>
      <% end%>
      <span class="text-info" id="guest-error"><%= flash[:notice] %></span>
      <!--<span class="text-info" id="guest-error"></span>-->
    </div>
  </div>
  <div class="ml-auto" style="display:inline-flex;">
    <div class="my-auto mr-4" style="width: 100%;">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if admin_signed_in? %>
            <li class="nav-item nav-link">
              <%= link_to admin_root_path, class:"link btn btn-light" do %>
                <i class="fas fa-users mr-1"></i>利用者一覧
              <% end %>
            </li>
            <li class="nav-item nav-link">
              <%= link_to admin_consultations_path, class:"link btn btn-light" do %>
                <i class="fas fa-comments mr-1"></i>相談管理
              <% end %>
            </li>
            <li class="nav-item nav-link">
              <%= link_to destroy_admin_session_path, method: :delete, class:"link btn btn-light" do %>
                <i class="fas fa-sign-out-alt mr-1"></i>ログアウト
              <% end %>
            </li>
          <% elsif end_user_signed_in? %>
            <li class="nav-item nav-link">
              <%= link_to new_bop_subject_path, class:"link btn btn-light" do %>
                <i class="fas fa-book-open mr-1"></i>科目登録
              <% end %>
            </li>
            <li class="nav-item nav-link">
              <%= link_to end_users_path, class:"link btn btn-light" do %>
                <i class="fas fa-home mr-1"></i>TOP
              <% end %>
            </li>
            <li class="nav-item nav-link">
              <%= link_to consultations_path, class:"link btn btn-light" do %>
                <i class="fas fa-comments mr-1"></i>相談広場
              <% end %>
            </li>
            <li class="nav-item nav-link">
              <%= link_to my_page_end_users_path, class:"link btn btn-light" do %>
                <i class="fas fa-user mr-1"></i>マイページ
              <% end %>
            </li>
            <li class="nav-item nav-link">
              <%= link_to destroy_end_user_session_path, method: :delete, class:"link btn btn-light" do %>
                <i class="fas fa-sign-out-alt mr-1"></i>ログアウト
              <% end %>
            </li>
          <% else %>
            <li class="nav-item nav-link">
              <%= link_to new_end_user_registration_path, class:"link btn btn-light" do %>
                <i class="fas fa-user-plus mr-1"></i>新規登録
              <% end %>
            </li>
            <li class="nav-item nav-link">
              <%= link_to new_end_user_session_path, class:"link btn btn-light" do %>
                <i class="fas fa-sign-in-alt mr-1"></i>ログイン
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_search.html.erb
<%= form_with url: search_path, method: :get do |f| %>
  <% if controller.controller_name == 'homes' %>
    <h5 class="mt-4">利用者検索</h5>
  <% else %>
    <h5 class="mt-4">タブ・キーワード検索</h5>
  <% end %>
  <div class="form-inline">
    <%= f.text_field :keyword, class: "form-control col-8" %>
    <%= f.submit "検索", class: "btn btn-secondary col-2 ml-3" %>
  </div>
  <div style="font-size: 10px;">
      ※#を付けて検索すると、タグを検索出来ます。<br>
      ※なにも付けない場合は、タイトル・本文を参照します。
  </div>
  <div class="text-danger"><%= flash.now[:keyword] %></div>
<% end %>

app/views/layouts/_search_view.html.erb
<div class="col-lg-10 col-md-11 mx-auto mt-5">
  <div class="card">
    <div class="m-5">
      <h3 class="d-inline">利用者一覧</h3>
      <%= render "layouts/search", search_path: search_path %>
      <h4 class="mt-3">"<%= params[:keyword] %>"の検索結果</h4>
      <% if @end_user.empty? %>
        <p class="text-danger" style="font-size: 20px;">検索結果はありません</p>
      <% end %>
      <table class="table mt-3">
        <thead>
          <tr>
            <th>氏名</th>
            <th>フリガナ</th>
            <th class="text-center">会員ステータス</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% end_user.each do |end_user| %>
            <tr>
              <td>
                <%= link_to admin_end_user_path(end_user) do %>
                  <%= end_user.full_name %>
                <% end %>
              </td>
              <td>
                <%= link_to admin_end_user_path(end_user) do %>
                  <%= end_user.full_name_kana %>
                <% end %>
              </td>
              <td class="text-center">
                <% if end_user.is_deleted == false %>
                  <div class="text-danger font-weight-bold">有効</div>
                <% else %>
                  <div class="text-secondary">退会</div>
                <% end %>
              </td>
              <td><%= link_to "編集", edit_admin_end_user_path(end_user), class: "btn btn-secondary" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CHOBO</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="shadow-sm">
      <%= render "layouts/header" %>
    </header>
    <main>
      <%= yield %>
    </main>
    <footer></footer>
  </body>
</html>